// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BeerStuff.DataAccess.Entities.BeerNetContext.Models
{
    public partial class BeerRecipeAdjunct
    {
        public uint BeerRecipeAdjunctId { get; set; }
        public uint BeerRecipeId { get; set; }
        public uint BeerAdjunctId { get; set; }
        public decimal Amount { get; set; }
        public string AmountUnit { get; set; }
        public string Notes { get; set; }

        public virtual BeerAdjunct BeerAdjunct { get; set; }
        public virtual BeerRecipe BeerRecipe { get; set; }
    }
}