// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BeerStuff.DataAccess.Entities.BeerNetContext.Models
{
    public partial class BeerRecipeGrain
    {
        public uint BeerRecipeGrainId { get; set; }
        public uint BeerRecipeId { get; set; }
        public uint BeerGrainId { get; set; }
        public decimal Amount { get; set; }

        public virtual BeerRecipe BeerRecipe { get; set; }
    }
}