// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BeerStuff.DataAccess.Entities.BeerNetContext.Models
{
    public partial class BeerRecipeYeast
    {
        public uint BeerRecipeYeastId { get; set; }
        public uint BeerRecipeId { get; set; }
        public uint BeerYeastId { get; set; }
        public decimal? StarterGallons { get; set; }
        public decimal? StarterMaltExtractOunces { get; set; }
        public DateTime RowCreated { get; set; }
        public DateTime RowModified { get; set; }

        public virtual BeerRecipe BeerRecipe { get; set; }
        public virtual BeerYeast BeerYeast { get; set; }
    }
}