// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BeerStuff.DataAccess.Entities.BeerNetContext.Models
{
    public partial class BeerRecipe
    {
        public BeerRecipe()
        {
            BeerRecipeAdjunct = new HashSet<BeerRecipeAdjunct>();
            BeerRecipeGrain = new HashSet<BeerRecipeGrain>();
            BeerRecipeHop = new HashSet<BeerRecipeHop>();
            BeerRecipeMashStep = new HashSet<BeerRecipeMashStep>();
            BeerRecipeNote = new HashSet<BeerRecipeNote>();
            BeerRecipeYeast = new HashSet<BeerRecipeYeast>();
        }

        public uint BeerRecipeId { get; set; }
        public string Name { get; set; }
        public decimal? TargetGravity { get; set; }
        public decimal? OriginalGravity { get; set; }
        public decimal? FinalGravity { get; set; }
        public decimal? AlcoholByVolume { get; set; }
        public decimal? BatchSize { get; set; }

        public virtual ICollection<BeerRecipeAdjunct> BeerRecipeAdjunct { get; set; }
        public virtual ICollection<BeerRecipeGrain> BeerRecipeGrain { get; set; }
        public virtual ICollection<BeerRecipeHop> BeerRecipeHop { get; set; }
        public virtual ICollection<BeerRecipeMashStep> BeerRecipeMashStep { get; set; }
        public virtual ICollection<BeerRecipeNote> BeerRecipeNote { get; set; }
        public virtual ICollection<BeerRecipeYeast> BeerRecipeYeast { get; set; }
    }
}