// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BeerStuff.DataAccess.Entities.BeerNetContext.Models
{
    public partial class BeerHop
    {
        public BeerHop()
        {
            BeerRecipeHop = new HashSet<BeerRecipeHop>();
        }

        public uint BeerHopId { get; set; }
        public string Name { get; set; }
        public decimal? AlphaAcid { get; set; }

        public virtual ICollection<BeerRecipeHop> BeerRecipeHop { get; set; }
    }
}