// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BeerStuff.DataAccess.Entities.BeerNetContext.Models
{
    public partial class BeerAdjunct
    {
        public BeerAdjunct()
        {
            BeerRecipeAdjunct = new HashSet<BeerRecipeAdjunct>();
        }

        public uint BeerAdjunctId { get; set; }
        public string Name { get; set; }
        public string Notes { get; set; }
        public DateTime RowCreated { get; set; }
        public DateTime RowModified { get; set; }

        public virtual ICollection<BeerRecipeAdjunct> BeerRecipeAdjunct { get; set; }
    }
}