package com.golfstats.kafka.service;

import com.golfstats.kafka.entity.Hole;
import com.golfstats.kafka.entity.Round;
import com.golfstats.kafka.model.GolfScoreEvent;
import com.golfstats.kafka.repository.HoleRepository;
import com.golfstats.kafka.repository.RoundRepository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.kafka.annotation.KafkaListener;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.Optional;

@Service
public class GolfScoreConsumerService {
    
    private static final Logger logger = LoggerFactory.getLogger(GolfScoreConsumerService.class);
    
    private final RoundRepository roundRepository;
    private final HoleRepository holeRepository;
    
    public GolfScoreConsumerService(RoundRepository roundRepository, HoleRepository holeRepository) {
        this.roundRepository = roundRepository;
        this.holeRepository = holeRepository;
    }
    
    @KafkaListener(topics = "${golf.kafka.topic.insert-new}", groupId = "${spring.kafka.consumer.group-id}")
    @Transactional
    public void consumeGolfScoreEvent(GolfScoreEvent event) {
        try {
            logger.info("Consuming golf score event: course={}, holeNumber={}", 
                event.getCourse(), event.getHoleNumber());
            
            // Find or create the round based on unique fields (round_id is now auto-generated)
            Round round = findOrCreateRound(event);
            Long roundId = round.getRoundId();
            
            // Process hole data (hole_id is auto-generated, so we don't set it)
            if (event.getHoleNumber() != null && roundId != null) {
                Hole hole = convertToHole(event, roundId);
                holeRepository.save(hole);
                logger.info("Inserted new hole: roundId={}, holeNumber={}, score={}", 
                    roundId, event.getHoleNumber(), event.getScore());
                
                // Update round score by recalculating sum of all holes for this round
                updateRoundScore(roundId);
            }
            
        } catch (Exception e) {
            logger.error("Error processing golf score event: course={}, holeNumber={}", 
                event.getCourse(), event.getHoleNumber(), e);
            throw new RuntimeException("Failed to process golf score event", e);
        }
    }
    
    /**
     * Finds an existing round or creates a new one based on unique fields.
     * The round_id is auto-generated by the database.
     */
    private Round findOrCreateRound(GolfScoreEvent event) {
        LocalDateTime dateInserted = parseDateTime(event.getDateInserted());
        
        // Try to find existing round by unique fields
        Optional<Round> existingRound = roundRepository.findByUniqueFields(
            event.getCourse(),
            event.getTeeType(),
            event.getHandicap(),
            dateInserted
        );
        
        if (existingRound.isPresent()) {
            logger.debug("Found existing round: roundId={}, course={}", 
                existingRound.get().getRoundId(), event.getCourse());
            return existingRound.get();
        }
        
        // Create new round (round_id will be auto-generated)
        Round round = new Round();
        round.setCourse(event.getCourse());
        round.setTeeType(event.getTeeType());
        round.setHandicap(event.getHandicap());
        round.setDateInserted(dateInserted);
        // Score will be calculated/updated later, set to 0 initially
        round.setScore(0);
        
        round = roundRepository.save(round);
        logger.info("Created new round: roundId={}, course={}", 
            round.getRoundId(), event.getCourse());
        
        return round;
    }
    
    /**
     * Converts GolfScoreEvent to Hole entity.
     * Note: hole_id is auto-generated, so we don't set it.
     * round_id is the generated ID from the Round entity.
     */
    private Hole convertToHole(GolfScoreEvent event, Long roundId) {
        Hole hole = new Hole();
        hole.setRoundId(roundId);
        hole.setHoleNumber(event.getHoleNumber());
        hole.setPar(event.getPar());
        hole.setStrokeIndex(event.getStrokeIndex());
        hole.setScore(event.getScore());
        hole.setPutts(event.getPutts());
        hole.setNetScore(event.getNetScore());
        hole.setStrokesTaken(event.getStrokesTaken());
        hole.setDateInserted(parseDateTime(event.getDateInserted()));
        // hole_id is auto-generated, so we don't set it
        return hole;
    }
    
    private LocalDateTime parseDateTime(LocalDateTime dateTime) {
        if (dateTime == null) {
            return LocalDateTime.now();
        }
        return dateTime;
    }
    
    /**
     * Updates the round's score by calculating the sum of all hole scores for the round
     */
    private void updateRoundScore(Long roundId) {
        try {
            Integer totalScore = holeRepository.sumScoreByRoundId(roundId);
            if (totalScore != null) {
                roundRepository.findById(roundId).ifPresent(round -> {
                    round.setScore(totalScore);
                    roundRepository.save(round);
                    logger.debug("Updated round score: roundId={}, totalScore={}", roundId, totalScore);
                });
            }
        } catch (Exception e) {
            logger.warn("Failed to update round score for roundId={}", roundId, e);
        }
    }
}

